  
sudo: required
language: python
services:
- docker

script:
- docker image build -t yariski/dockertest1 .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push yariski/dockertest1
  #test